version: '3.5'

services:
    frontend:
      image: frontend
    backend:
      image: backend
      environment:
        - REDIS=redis
        - DB_USERNAME=postgres
        - DB_PASSWORD=example
        - DB_NAME=db
        - DB_HOST=db  
      depends_on:
        - redis
        - db  
    redis:
      image: redis
      container_name: 'redis'
    nginx:
      image: nginx
      ports:
        - 80:80
      depends_on:
        - backend
    db:
      image: postgres
      restart: unless-stopped
      environment:
        - POSTGRES_PASSWORD=example
        - POSTGRES_DB=db
        - PGPASSWORD=example
      container_name: db      
