version: '2.0'

services:
    backend:
        image: dmlsamftaq/backend-exercise
        ports:
            - 8000:8000
    frontend:
        image: dmlsamftaq/frontend-exercise
        ports:
            - 5000:5000
