version: '3.5'

services:
  backend:
    image: dmlsamftaq/backend-exercise
    environment:      
      - DB_USERNAME=postgres
      - DB_PASSWORD=example
      - DB_NAME=db
      - DB_HOST=db
    ports:
      - 8000:8000
    depends_on: 
      - db
  frontend:
    image: dmlsamftaq/frontend-exercise
    ports:
      - 5000:5000
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=db
      - PGPASSWORD=example
    container_name: db_redmine
