version: '3.5'

services:
    frontend:
      image: frontend
      ports:
        - 5000:5000
    backend:
      image: backend
      ports:
        - 8000:5000
    nginx:
      image: nginx
      ports:
        - 80:80
